config/routes.rb
Demo::Application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations'}

  root to: 'static_pages#home'

  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/terms', to: 'static_pages#terms'
  get '/confirm-code', to: 'static_pages#confirm_code'

  resources :projects do
    resources :sprints
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :user
	has_many :sprints
end

app/models/rating.rb
class Rating < ActiveRecord::Base
	belongs_to :sprint
end

app/models/sprint.rb
class Sprint < ActiveRecord::Base
  belongs_to :project
  has_many :ratings
  # has_one :token

  before_save :generate_token

  def generate_token
    while true
      alphanumeric = (0...3).map { [('a'..'z').to_a[rand(26)], (0..9).to_a[rand(10)]] }.join.upcase
      break if Sprint.where(["token = ? and votes = ?", alphanumeric, 0]).empty?
    end
    
    self.token = alphanumeric
  end
end

app/models/token.rb
class Token < ActiveRecord::Base
	belongs_to :sprint
end

app/models/user.rb
# User
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :projects
end

app/controllers/application_controller.rb
# The majority of The Supplejack Website code is Crown copyright (C) 2014,
# New Zealand Government, and is licensed under the GNU General Public License,
# version 3. Some components are third party components that are licensed under
# the MIT license or other terms.
# See https://github.com/DigitalNZ/supplejack_website for details.
#
# Supplejack was created by DigitalNZ at the National Library of NZ and
# the Department of Internal Affairs.
# http://digitalnz.org/supplejack

# Application controller
class ApplicationController < ActionController::Base
  protect_from_forgery

  after_filter :store_location

  def store_location
    # store last url
    # this is needed for post-login redirect to whatever the user last visited.
    return unless request.get? && (request.format == 'text/html' ||
                                   request.content_type != 'text/html')

    exception_paths = ['/users/sign_in', '/users/sign_up',
                       '/users/password/new', '/users/password/edit',
                       '/users/confirmation', '/users/sign_out']

    session[:previous_url] = request.fullpath if !exception_paths.include?(request.path) && !request.xhr?
  end

  def after_sign_in_path_for(*)
    projects_path
    # session[:previous_url] || root_path
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!

  def index
    @projects = current_user.projects
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    current_user.projects.create(project_params)
    redirect_to projects_path
  end

  def project_params
    params.require(:project).permit(:name, :description)
  end
end

app/controllers/registrations_controller.rb
# Registraion controller is used for user creation
class RegistrationsController < Devise::RegistrationsController
  def create
    build_resource(user_params)

    if resource.save
      if resource.active_for_authentication?
        # set_flash_message :notice, :signed_up #if is_navigational_format?
        sign_in(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        # set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_navigational_format?
        expire_session_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      resource.destroy unless resource.new_record?
      clean_up_passwords resource
      respond_with resource
    end
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/sprints_controller.rb
class SprintsController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def show
    @sprint = Sprint.find(params[:id])
  end

  def new
    @project = Project.find(params[:project_id])
    @sprint = @project.sprints.new
  end

  def create
    sprint = Sprint.create(sprint_params)
    redirect_to project_sprint_path(project_id: 1, id: sprint.id)
  end

  def sprint_params
    params.require(:sprint).permit(:votes)
  end  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    redirect_to projects_path if current_user
  end

  def become_a_partner
  end

  def about
  end

  def contact
  end

  def terms
  end

  def base_template
  end

  def confirm_code
  end
end

app/helpers/application_helper.rb
# The majority of The Supplejack Website code is Crown copyright (C) 2014,
# New Zealand Government, and is licensed under the GNU General Public License,
# version 3. Some components are third party components that are licensed under
# the MIT license or other terms.
# See https://github.com/DigitalNZ/supplejack_website for details.
#
# Supplejack was created by DigitalNZ at the National Library of NZ and
# the Department of Internal Affairs.
# http://digitalnz.org/supplejack

# Application Helper
module ApplicationHelper
  def title(*args)
    args.delete_if { |e| e.blank? }
    args = args.map { |e| truncate(e, length: 40) }
    title = (args + [t('site_title')]).join(' | ')
    content_for(:title) { title }
  end

  def site_title(yield_title = nil)
    yield_title.presence || t('site_title')
  end

  def active_scope_filter(title, options = {})
    active_class = 'country-filter'
    scope_options = options[:tab].present? ? options[:tab] : 'all'
    scope_params = @search.params[:tab].present? ? @search.params[:tab] : 'all'

    active_class += ' active-scope' if scope_options == scope_params

    content_tag(:li, class: active_class) do
      link_to title, records_path(options)
    end
  end

  def search_tab_options(options, tab)
    options.delete(:page)
    tab.eql?('All') ? options : options.merge(tab: tab)
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">x</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/records_helper.rb
# The majority of The Supplejack Website code is Crown copyright (C) 2014,
# New Zealand Government, and is licensed under the GNU General Public License,
# version 3. Some components are third party components that are licensed under
# the MIT license or other terms.
# See https://github.com/DigitalNZ/supplejack_website for details.
#
# Supplejack was created by DigitalNZ at the National Library of NZ and
# the Department of Internal Affairs.
# http://digitalnz.org/supplejack

# Record Helper
module RecordsHelper
  def record_thumbnail(record, search = nil)
    image_options = {}
    search ||= Search.new
    search_options = search.options.try(:any?) ? search.options : nil

    image_options[:alt] ||= record.title
    image_options[:title] ||= image_options[:alt]

    content = content_tag(:div, link_to(image_tag(record.image_url, image_options), record_path(record.id, search: search_options)))
    content.html_safe
  end

  def source_contributor_name(record)
    content_tag(:p, record.source_contributor_name.join(', ').html_safe)
  end

  def search_tab
    @search_tab ||= SearchTab.new(params[:tab])
  end

  def filter_facets
    # facets that we want to ignore/exclude
    blacklist = ['type']
    facets = Hash[@search.facets.map { |facet| [facet.name.to_s, facet.values] }]
    # Remove empty facets & unwanted facets
    facets.delete_if { |facet, values| values.empty? || blacklist.include?(facet) }
  end

  def filter_class(filter_name)
    filter_name.strip.gsub(/[^[:alnum:]]/, '').downcase
  end

  def date_parser_for(string)
    Date.parse string rescue return string
    Date.parse(string).strftime('%d %b %Y')
  end
end

app/helpers/sprints_helper.rb
module SprintsHelper
end

app/views/layouts/_header_home.html.haml
%body
  %header
    .container
      = render "layouts/header_nav"

app/views/layouts/_header_nav.html.haml
/ # The majority of The Supplejack Website code is Crown copyright (C) 2014,
/ # New Zealand Government, and is licensed under the GNU General Public License,
/ #version 3. Some components are third party components that are licensed under
/ # the MIT license or other terms.
/ # See https://github.com/DigitalNZ/supplejack_website for details.
/ #
/ # Supplejack was created by DigitalNZ at the National Library of NZ and
/ # the Department of Internal Affairs.
/ # http://digitalnz.org/supplejack
%button.menu menu
%nav.menu
  .menu-inner
    / <haml_loud> link_to &quot;Become a Partner&quot;, become_a_partner_path </haml_loud>
    = link_to "Contact", contact_path
    / <haml_loud> link_to &quot;Terms of use&quot;, terms_path </haml_loud>
    = link_to "About", about_path

app/views/layouts/application.html.haml
!!!
%html
	/ paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
	/[if lt IE 7 ] <html class="ie6" lang="en">
	/[if IE 7 ] <html class="ie7" lang="en">
	/[if IE 8 ] <html class="ie8" lang="en">
	/ [if (gte IE 9)|!(IE)]><!
	/ <![endif]
	= render "shared/head"

	%body{ class: yield(:body_class) }
		= render "shared/header"
		- if notice
			%p.alert.alert-success= notice
		- if alert
			%p.alert.alert-danger= alert

		.main= yield

		= render "shared/footer"

app/views/layouts/story.html.haml
!!!
%html
	/ paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/
	/[if lt IE 7 ] <html class="ie6" lang="en">
	/[if IE 7 ] <html class="ie7" lang="en">
	/[if IE 8 ] <html class="ie8" lang="en">
	/ [if (gte IE 9)|!(IE)]><!
	/ <![endif]
	= render "shared/head"

	%body
		= render "shared/header"
		- if notice
			%p.alert.alert-success= notice
		- if alert
			%p.alert.alert-danger= alert

		.story= yield

		= render "shared/footer"

app/views/projects/index.html.haml
.row
	.medium-8.columns
		%h3 Projects

		%table
			%thead
				%tr
					%th{:width => "150"} Project
					%th{:width => "350"} Description
					%th{:width => "75"} View
			%tbody
				- @projects.each do |project|
					%tr
						%td 
							= project.name
						%td 
							= project.description
						%td 
							= link_to "Show", project_path(project.id)


	.medium-4.columns
		%h3 Manage
		= link_to 'Add Project', new_project_path, class: 'button tiny round'

app/views/projects/new.html.haml
.row
  .medium-12.columns
    %h1 Create New Project

.row
  .medium-6.columns

    = form_for @project do |f|
      %label
        %strong Project Name
      = f.text_field :name

      %label
        %strong Description
      = f.text_field :description

      .actions
        = f.submit "Create", class: 'button round'


  .medium-6.columns
    %h2 New project will have sprints automatically generated in future
    .help-inset
      Some text
      %br
      Some more text

app/views/projects/show.html.haml
.row
  .medium-6.columns
    %h1
      = @project.name
    = @project.description


  .medium-6.columns
    %h2 Manage

    %ul.button-group.round
      %li
        = link_to 'Edit', edit_project_path(@project.id), class: 'button round tiny'
      %li
        = link_to 'Delete', edit_project_path(@project.id), data: {confirm: "This will permenantly delete project #{@project.name}. Are you sure?"}, class: 'button alert round tiny'      

    = link_to 'Create Sprint', new_project_sprint_path(project_id: @project.id), class: 'button round tiny'

app/views/shared/_add_to_set.html.erb
<%= render partial: "shared/add_to_set_logged_#{logged_in ? 'in' : 'out'}", locals: {record_id: record.id} %>

app/views/shared/_add_to_set_logged_in.html.erb
<span class="add-to-set" data-record-id="<%= record_id %>">+</span>
<div class="add-to-set-popup logged-in" style="display: none;">
  <ul class="sets-container">
  </ul>
  <form>
    <label>
      New set <input type="text" class="add-to-new-set-name" />
    </label>
    <input type="submit" class="add-to-new-set-submit" value="Create" data-record-id="<%= record_id %>"/>
  </form>
</div>

app/views/shared/_add_to_set_logged_out.html.erb
<span class="add-to-set">+</span>
<div class="add-to-set-popup" style="display: none;">
  <p>You need to <%= link_to "sign-in", new_user_session_path %> or <%= link_to "sign-up", new_user_registration_path %> to save items</p>
</div>

app/views/shared/_footer.html.haml
/
  \# The majority of The Supplejack Website code is Crown copyright (C) 2014, New Zealand Government,
  \# and is licensed under the GNU General Public License, version 3. Some components are
  \# third party components that are licensed under the MIT license or other terms.
  \# See https://github.com/DigitalNZ/supplejack_website for details.
  \#
  \# Supplejack was created by DigitalNZ at the National Library of NZ and the Department of Internal Affairs.
  \# http://digitalnz.org/supplejack
%footer
  .row
    %nav
      / <haml_loud> link_to &quot;Become a Partner&quot;, become_a_partner_path </haml_loud>
      / <haml_loud> link_to &quot;Contact&quot;, contact_path </haml_loud>
      = link_to "Terms of use", terms_path
= javascript_include_tag "application"

app/views/shared/_head.html.haml
%head
  %title= site_title(yield(:title))
  %meta{:charset => "utf-8"}/
  / Uncomment to make IE8 render like IE7
  / <meta http-equiv="X-UA-Compatible" content="IE=7" />
  / Set the viewport width to device width for mobile
  %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
  = stylesheet_link_tag    "application"
  = javascript_include_tag "vendor/modernizr.custom"
  = csrf_meta_tags

app/views/shared/_header.html.haml
%header
	= render "shared/menu"
	.container

app/views/shared/_menu.html.haml
/
  \# The majority of The Supplejack Website code is Crown copyright (C) 2014, New Zealand Government,
  \# and is licensed under the GNU General Public License, version 3. Some components are
  \# third party components that are licensed under the MIT license or other terms.
  \# See https://github.com/DigitalNZ/supplejack_website for details.
  \#
  \# Supplejack was created by DigitalNZ at the National Library of NZ and the Department of Internal Affairs.
  \# http://digitalnz.org/supplejack
.contain-to-grid.sticky
  %nav.top-bar{'data-topbar' => true, role: "navigation"}
    %ul.title-area
      %li.name
        %h1= link_to t('site_title'), root_url
      %li.toggle-topbar.menu-icon= link_to "Menu", '#'

    %section.top-bar-section
      %ul.left

                
      %ul.right
        %li= link_to 'Contact', '/contact'
        %li= link_to 'About', '/about'

        - if user_signed_in?
          %li.has-dropdown
            %a= current_user.email.split('@').first
            %ul.dropdown
              %li= link_to 'Edit profile', edit_user_registration_path
              %li= link_to "Logout", destroy_user_session_path, method: :delete      
        - else 
          %li= link_to "Sign up", new_user_registration_path
          %li= link_to "Login", new_user_session_path

app/views/shared/_search.html.haml
/
  \# The majority of The Supplejack Website code is Crown copyright (C) 2014, New Zealand Government,
  \# and is licensed under the GNU General Public License, version 3. Some components are
  \# third party components that are licensed under the MIT license or other terms.
  \# See https://github.com/DigitalNZ/supplejack_website for details.
  \#
  \# Supplejack was created by DigitalNZ at the National Library of NZ and the Department of Internal Affairs.
  \# http://digitalnz.org/supplejack
= form_tag '/confirm-code', :method => :get, class: 'search clearfix' do
  = hidden_field_tag("tab", params[:tab]) if params[:tab].present?
  = text_field_tag "code", '', class: 'search-input', placeholder: t('records.enter_search')
  = submit_tag "Search", class: "search-button"

app/views/sprints/new.html.haml
.row
  .medium-12.columns
    %h1 Create New Sprint

.row
  .medium-6.columns

    = form_for [@project, @sprint] do |f|
      .row
        .small-3.columns
          %label
            %strong Votes
          = f.select :votes, (1..100)

      .row
        .small-3.columns
          .actions
            = f.submit "Create", class: 'button round'


  .medium-6.columns
    %h2 Votes?
    .help-inset
      Number of scrum members who are rating the sprint.
      %br
      The create action will create a sprint and a token for it.

app/views/sprints/show.html.haml
.row
  .medium-6.columns
    %h1
      = @sprint.created_at
    = @sprint.token


  .medium-6.columns
    %h2 Manage

    / %ul.button-group.round
    /   %li
    /     = link_to 'Edit', edit_project_path(@project.id), class: 'button round tiny'
    /   %li
    /     = link_to 'Delete', edit_project_path(@project.id), data: {confirm: "This will permenantly delete project #{@project.name}. Are you sure?"}, class: 'button alert round tiny'      

    / = link_to 'Create Sprint', new_project_sprint_path(project_id: @project.id), class: 'button round tiny'

app/views/static_pages/about.html.haml
.container.static
  %h1 About
  %p This web app is designed to record and visualize how well a Srum performs.
  %p Or in other words how do your Scrum feel.

app/views/static_pages/base_template.haml
/
  \# The majority of The Supplejack Website code is Crown copyright (C) 2014, New Zealand Government,
  \# and is licensed under the GNU General Public License, version 3. Some components are
  \# third party components that are licensed under the MIT license or other terms.
  \# See https://github.com/DigitalNZ/supplejack_website for details.
  \#
  \# Supplejack was created by DigitalNZ at the National Library of NZ and the Department of Internal Affairs.
  \# http://digitalnz.org/supplejack
.container.static
  %section
    %h1 Main page title
    %p.blurb
      Preamble, Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur sed gravida arcu,
      eget mollis nunc. Aenean molestie rhoncus ipsum, ac tempor erat molestie eu.
      Donec tincidunt leo nec enim rutrum pulvinar.
    %h3 General subtitle
    %p
      We aim to make New Zealand digital content more useful. This includes helping people use digital material from libraries, museums, government departments, publicly funded organisations, the private sector, and community groups.
    %h2 Section title
    %h3 General subtitle
    %p
      We aim to make New Zealand digital content more useful. This includes helping people use digital material from libraries, museums, government departments, publicly funded organisations, the private sector, and community groups.
    %h3 Example of bulleted list
    %ul
      %li
        %span Number one
      %li
        %span Number two
    %h3 Example of numbered list
    %ol
      %li
        %span Number one
      %li
        %span Number two
    = succeed "." do
      %a{:href => "#"} I am a link
    = succeed "." do
      %a{:href => "#"} and what do you have it I am another link
  .sidebar
    %h2 Parent title
    %ul.secondary-nav
      %li
        %a{:href => "/make-it-digital/getting-started-with-digitisation"} Getting Started with Digitisation
      %li
        %a{:href => "/make-it-digital/selecting-for-digitisation"} Selecting for Digitisation
      %li.active
        %a{:href => "/make-it-digital/creating-digital-content"} Creating Digital Content
        %ul.children
          %li#page_79.page
            %a{:href => "/make-it-digital/creating-digital-content/photography-and-imaging"} Photography and Imaging
          %li#page_80.page
            %a{:href => "/make-it-digital/creating-digital-content/creating-digital-text"} Creating Digital Text
          %li#page_81.page
            %a{:href => "/make-it-digital/creating-digital-content/creating-digital-audio"} Creating Digital Audio
          %li#page_82.page
            %a{:href => "/make-it-digital/creating-digital-content/creating-digital-video"} Creating Digital Video
          %li#page_83.page
            %a{:href => "/make-it-digital/creating-digital-content/digitisation-resources"} Digitisation Resources
      %li
        %a{:href => "/make-it-digital/describing-digital-content"} Describing Digital Content
      %li
        %a{:href => "/make-it-digital/managing-digital-content"} Managing Digital Content
      %li
        %a{:href => "/make-it-digital/preserving-digital-content"} Preserving Digital Content
      %li
        %a{:href => "/make-it-digital/enabling-use-re-use"} Enabling Use &amp; Re-use

app/views/static_pages/become_a_partner.html.haml
/
  \# The majority of The Supplejack Website code is Crown copyright (C) 2014, New Zealand Government,
  \# and is licensed under the GNU General Public License, version 3. Some components are
  \# third party components that are licensed under the MIT license or other terms.
  \# See https://github.com/DigitalNZ/supplejack_website for details.
  \#
  \# Supplejack was created by DigitalNZ at the National Library of NZ and the Department of Internal Affairs.
  \# http://digitalnz.org/supplejack
.container.static
  %h1 Become a Partner
  %p To become a contributor to this pilot website you will need to have digital items from your collection online so we can point to them, alternatively you may be planning a digitisation project that we can discuss with you.
  %p
    The following information provides an overview of how we can work with you. It is important that you also read and understand the
    %a{:href => "http://www.digitalnz.org.nz/about/terms-of-use/metadata-contribution-terms"} Metadata Contribution Terms
    we will provide to you, as partners of this service will need to agree to the sharing of their descriptive metadata. This agreement is modelled on the
    %a{:href => "http://www.digitalnz.org.nz/about/terms-of-use/metadata-contribution-terms"} Metadata Contribution Terms
    agreement used by the National Library of New Zealand&#x2019;s DigitalNZ service.
  %p Being part of this pilot project means that the National Library Board of Singapore (NLB):
  %ul
    %li Will harvest, copy  cache your metadata, including small thumbnails, so it can be made accessible and searchable on the pilot platform.
    %li NLB may make larger sized thumbnails so your items display attractively on the pilot platform.
    %li
      Your metadata can be made available via the pilot platform API (use of which is subject to the
      %a{:href => "http://www.digitalnz.org.nz/about/terms-of-use/developer-api-terms-of-use"} Developer API
      Terms modelled on the National Library of New Zealand&#x2019;s DigitalNZ service).
    %li Your metadata may be cached for up to 30 days by users of the pilot platform API.
    %li Your metadata cannot be used for commercial purposes without your permission.
  %p NLB will:
  %ul
    %li Provide clear attribution of your items (displaying the source and the URL of each item) on the pilot platform.
    %li Promptly remove your metadata from the pilot platform website at your request.
    %li Give you 30 days notice of any changes to the Metadata Contributor Terms.
  %p
    To confirm your participation in this pilot please Ms KHOR Su Min at
    %a{:href => "mailto:Su_Min_KHOR@nlb.gov.sg"} Su_Min_KHOR@nlb.gov.sg
    and Ms LEE Mei Chen at
    %a{:href => "mailto:MEI_CHEN_LEE@nlb.gov.sg"} MEI_CHEN_LEE@nlb.gov.sg
    to indicate your interest.
  %p If you wish to discuss any of these details, please don&#x2019;t hesitate to contact us, and thank you for helping us make our region's digital content easier to find, share and use.

app/views/static_pages/contact.html.haml
/
  \# The majority of The Supplejack Website code is Crown copyright (C) 2014, New Zealand Government,
  \# and is licensed under the GNU General Public License, version 3. Some components are
  \# third party components that are licensed under the MIT license or other terms.
  \# See https://github.com/DigitalNZ/supplejack_website for details.
  \#
  \# Supplejack was created by DigitalNZ at the National Library of NZ and the Department of Internal Affairs.
  \# http://digitalnz.org/supplejack
.container.static
  %h1 Contact

app/views/static_pages/home.html.haml
.row.home
	.centerScreen
		%h1.logo= t('site_title')
		= render "shared/search"

		%p.introText= t('home.intro').html_safe

app/views/static_pages/terms.html.haml
/
  \# The majority of The Supplejack Website code is Crown copyright (C) 2014, New Zealand Government,
  \# and is licensed under the GNU General Public License, version 3. Some components are
  \# third party components that are licensed under the MIT license or other terms.
  \# See https://github.com/DigitalNZ/supplejack_website for details.
  \#
  \# Supplejack was created by DigitalNZ at the National Library of NZ and the Department of Internal Affairs.
  \# http://digitalnz.org/supplejack
.container.static
  %h1 Terms of Use